name: Build and Push Docker Images

on:
  push:
    branches:
      - master  # or the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          
          username: ${{ secrets.AzureAppService_ContainerUsername_fe854f261d1b42899e8c738abbca4a79 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_dad4001d93c94e248eea45e4c4a20561 }}


      # Build and push nginx image
      - name: Build and push nginx image
        uses: docker/build-push-action@v3
        with:
          context: ./nginx  # Set the build context to the nginx directory
          file: ./nginx/Dockerfile  # Specify the Dockerfile inside the nginx directory
          push: true
          tags: index.docker.io/yourdockerhubusername/nginx:latest  # Tag for the nginx image

      # Build and push proxy image
      - name: Build and push proxy image
        uses: docker/build-push-action@v3
        with:
          context: ./proxy  # Set the build context to the proxy directory
          file: ./proxy/Dockerfile  # Specify the Dockerfile inside the proxy directory
          push: true
          tags: index.docker.io/yourdockerhubusername/proxy:latest  # Tag for the proxy image
