# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - easytestok

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d4e71b1313e34dc3a8dc95e8b0a3f34c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_208a67b4940749ed834f5420598b4c89 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d4e71b1313e34dc3a8dc95e8b0a3f34c }}/nginx:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'easytestok'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_361fe04ccc564d0aa0657502fddcc1ac }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d4e71b1313e34dc3a8dc95e8b0a3f34c }}/nginx:${{ github.sha }}'